services:
  - type: web
    runtime: node
    name: detailerz
    buildCommand: cd app && npm ci --include=dev && npm --prefix web ci --include=dev && npm run build
    startCommand: cd app && npm start
    healthCheckPath: /health
